language: node_js
node_js:
    - "4.1"

branches:
    only:
        - master
env:
    global:
        - PATH=$PATH:node_modules/.bin

deploy:
    provider: npm
    api_key: $API_KEY
    email: $NPM_EMAIL
    skip_cleanup: true

before_install:
    - source .travis/prepare_git.sh

install:
    - npm install

script:
    - npm test

after_success:
    - npm run build-commonjs
    - npm run build-browser
    - source .travis/deploy.sh
